### ISSUE TITLE
guzzle/guzzle is abandoned

### ISSUE THREAD

**Issue by railto** [codeclimate/php-test-reporter#103]
When installing the package the following message is displayed by composer:

Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead.

Would be a good idea to not use abandoned packages

**Comment by localheinz** [comment]
@railto 

Absolutely, I agree!

Let's make that happen!

**Comment by localheinz** [comment]
@railto 

All we need is a lot of people casting their vote right here

* https://github.com/satooshi/php-coveralls/issues/203

It has already been updated upstream, they just need to tag a release!

**Comment by daften** [comment]
This is starting to be a problem, since guzzle3 still requires "symfony/class-loader": "~2.1" and a lot of packages require ~3.0 for that package. 
Can a 2.x release be made without windows compatibility, to at least move forward? :)

**Comment by jhabdas** [comment]
https://github.com/marketplace

**Comment by jhabdas** [comment]
https://github.com/marketplace/codecov

**Comment by dblandin** [comment]
Hey @railto,

Thank for the issue. We're winding down development on this PHP-specific reporter.

I'd recommend checking out our new test reporter and migrating to it if you're interested!

https://github.com/codeclimate/test-reporter
https://codeclimate.com/changelog/591c99570d51f6481f001291

It's decoupled from the coverage tool used to generate the report, distributed as a static binary, and has support for parallelized builds. 🎉
