### ISSUE TITLE
PHP error via travis.ci

### ISSUE THREAD

**Issue by thomasplevy** [codeclimate/php-test-reporter#107]
I've just started trying to set up code climate and I think I finally got everything working but builds run via travis are failing with the following error:

```
PHP Parse error:  syntax error, unexpected 'foreach' (T_FOREACH) in /home/travis/build/gocodebox/lifterlms/vendor/codeclimate/php-test-reporter/composer/bin/test-reporter on line 13

Parse error: syntax error, unexpected 'foreach' (T_FOREACH) in /home/travis/build/gocodebox/lifterlms/vendor/codeclimate/php-test-reporter/composer/bin/test-reporter on line 13
```

I tried to fix this locally but I can't get it to successfully run via command line either, hitting namespace errors when I try to execute the file at ./vendor/bin/test-reporter.

I tried to get a .phar to try it that way but I can't find .phars in any of the releases here

Thanks,

**Comment by ABaldwinHunter** [comment]
@thomasplevy thanks for the report! hoping that pr fixes this issue.

**Comment by ABaldwinHunter** [comment]
@thomasplevy curious about what version of php you're using. 

Also, merged that PR. can you try updating to use latest master and see if that fixes the issue you were seeing?

**Comment by thomasplevy** [comment]
@ABaldwinHunter that appears to have fixed it thanks, was running tests on 5.6, 7, 7.1

While you're paying attention to me I have an unrelated issue I can't seem to find a repo token for my repo (it's open source) does code coverage not apply to the OS repos via code climate?


Thanks for the speedy update!

**Comment by ABaldwinHunter** [comment]
@thomasplevy np! yep code coverage totally applies to OS repos!

You should be able to find the token under `test coverage` tab in your repo settings.

For ref here're some potentially helpful docs in order of anticipated utility: 
- [setting up test coverage](https://docs.codeclimate.com/docs/setting-up-test-coverage)
- [adding an OSS repo to Code Climate](https://docs.codeclimate.com/docs/open-source-free#section-adding-an-oss-github-repo-to-code-climate)
- [trouble shooting a missing settings link for OSS repo](https://docs.codeclimate.com/docs/missing-settings-link)

With OSS you can also enable PR integration and use our [browser extension](https://codeclimate.com/browser-extension) for chrome if you're a chrome user.

Feel free to ping me with any other queries. Let me know if you have any other trouble finding the repo token.

**Comment by thomasplevy** [comment]
@ABaldwinHunter ah it seems I had linked my account but not the organization.

Thanks for your help!!!
