### ISSUE TITLE
Provide missing GITHUB_API_KEY for Travis CI integration

### ISSUE THREAD

**Issue by localheinz** [codeclimate/php-test-reporter#118]
#### Steps required to reproduce the problem

1. tag a commit and push to `origin` (or tag it via GitHub UI)

#### Expected Result

* a `PHAR` is automatically created on the PHP5.3 build on Travis, see [`.travis.yml`](https://github.com/codeclimate/php-test-reporter/blob/eab9ac233f23a4c12a12755793750f22fc46dd3e/.travis.yml#L9-L10)

#### Actual Result

* a `PHAR` isn't automatically created because the `GITHUB_API_KEY` environment variable doesn't exist, see for example [Job #312.2](https://travis-ci.org/codeclimate/php-test-reporter/jobs/202048701#L303)

Related to #54.

💁‍♂️ What needs to be done here is

* create a GitHub API token with sufficient permissions (I assume we need to have write permissions, too)
* add this token either via https://travis-ci.org/codeclimate/php-test-reporter/settings, or https://docs.travis-ci.com/user/encryption-keys/#Usage

❗️ Danger zone, make sure to securely add this token, it should not be exposed to anyone (unless it is encrypted into `.travis.yml`).

**Comment by dblandin** [comment]
Hey @localheinz,

I just added a GitHub access token to the TravisCI project via the Environment Variables configuration section.

It currently has the `public_repo` scope. Let me know if the token needs additional permissions.

Thanks!

**Comment by dblandin** [comment]
Hey @localheinz,

Anything I can do to push this along?

**Comment by dblandin** [comment]
Going to go ahead and close this issue as the environment variable is now available during CI runs.
