### ISSUE TITLE
Sending coverage to custom server sets Host header to codeclimate.com

### ISSUE THREAD

**Issue by solonrice** [codeclimate/php-test-reporter#121]
#### Steps required to reproduce the problem

1. Setup custom server at URL that is not codeclimate.com
2. Run code coverage with env CODECLIMATE_API_HOST set to that URL
3. Observe request headers

#### Expected Result

* Host header should be customizable or default to the host of URL set in CODECLIMATE_API_HOST. For example, if the env var is set to https://codeclimate.mydomain.com then Host header should be set to codeclimate.mydomain.com.
* The other option is to just remove the hard-coded Host header.

#### Actual Result

* Host header is always codeclimate.com, which may cause custom server to redirect or not work if the custom server rejects invalid Host header names.

**Comment by solonrice** [comment]
This is caused by line 38 in `/src/TestReporter/ApiClient.php` in the options array.

**Comment by GordonDiggs** [comment]
Hey @solonrice thanks for opening this issue! If you want to open a pull request, I'd happily merge it, but don't know when we will have time to address it. Additionally, we are starting work on a new test reporter (https://github.com/codeclimate/test-reporter) that will be ready soon and will replace this one. If you are interested in hearing when that is ready, we are tracking an issue [here](https://github.com/codeclimate/test-reporter/issues/24)!

Also going to cc @localheinz in case you have some free time and want to look at this

**Comment by solonrice** [comment]
Thank you for the quick response. I didn't have time at the moment to fix, but when I do, I will be sure to add a PR. I will probably just make it parse the host from the URL which will be any easy fix and not break anyone who depends on the Host header.

**Comment by localheinz** [comment]
Ha, sorry for the delay, will take a look!

**Comment by mrrsm** [comment]
This actually still partially exists as the fix I submitted only applied to using fopen and not curl.
