### ISSUE TITLE
Phar Package not found

### ISSUE THREAD

**Issue by mimmi20** [codeclimate/php-test-reporter#123]
#### Steps required to reproduce the problem

a.
  a.1. Edit your projects .travis.yml
  a.2. add the wget command, mentinioned in the readme.md using the tester as Phar tool 

b. or try to run the wget command on a linux shell

#### Expected Result

* the phar file is downloaded

#### Actual Result

```
wget -c "https://github.com/codeclimate/php-test-reporter/releases/download/0.4.4/codeclimate-test-reporter.phar"
--2017-04-13 08:41:11--  https://github.com/codeclimate/php-test-reporter/releases/download/0.4.4/codeclimate-test-reporter.phar
Auflösen des Hostnamen »github.com (github.com)«... 192.30.253.113, 192.30.253.112
Verbindungsaufbau zu github.com (github.com)|192.30.253.113|:443... verbunden.
HTTP-Anforderung gesendet, warte auf Antwort... 404 Not Found
2017-04-13 08:41:12 FEHLER 404: Not Found.
```

**Comment by lreisoliveira** [comment]
+ 1

**Comment by dblandin** [comment]
Hey @mimmi20 @lreisoliveira,

While we do have some tasks for generating phar files, we never got around to automating their generation and release. Sorry about that!

I'd recommend checking out our new test reporter: https://github.com/codeclimate/test-reporter

https://codeclimate.com/changelog/591c99570d51f6481f001291

It's decoupled from the coverage tool used to generate the report, distributed as a static binary, and has support for parallelized builds.
