### ISSUE TITLE
Update to README and docs

### ISSUE THREAD

**Issue by enygma** [codeclimate/php-test-reporter#17]
FYI if you don't use something like `export` in bash, you're not going to get the `CODECLIMATE_REPO_TOKEN` to be available inside the PHP script:

`export CODECLIMATE_REPO_TOKEN=token-goes-here`

If someone copy & pasted from the README and site docs (on the Test Coverage page) they wouldn't get it and the reporter will silently fail with a 401 on the request.

**Comment by jonathancadepowers** [comment]
@daBayrus We should work great with Cake. The only requirement that we have (from a test coverage stand-point) is that your testing framework can generate coverage data into a `clover.xml` file. You'll then pass this file to our reporter, and everything else is taken care of for you. More info here: https://github.com/codeclimate/php-test-reporter#installation

**Comment by renatomefidf** [comment]
@enygma is my PR #30 I created a new option "--codeclimate-repo-token" and also updated the docs, the fork is updated and I'm using it on my own projects!

**Comment by dblandin** [comment]
@enygma,

We have since updated the README and docs to include the following invocation instruction:

```
CODECLIMATE_REPO_TOKEN=abc ./vendor/bin/test-reporter
```

which should properly expose the environment variable to the test reporter process.

Going to go ahead and close this issue. Thanks!
