### ISSUE TITLE
Add exception/failure when HTTP request != 200

### ISSUE THREAD

**Issue by enygma** [codeclimate/php-test-reporter#18]
When the HTTP request to the server fails for some reason (either the bad cert issue or a 401 like I was seeing in the test reporter), a failure message should be presented to the user.

**Comment by dblandin** [comment]
Hi @enygma, are you still experiencing this issue?

It looks like we have been handling non-200 status codes as of https://github.com/codeclimate/php-test-reporter/commit/eec6e28f8528d9b75dc122e23db2a1c810801370.

**Comment by dblandin** [comment]
Going to close this issue for now. Feel free to reopen if this is still an issue. Thanks!
