### ISSUE TITLE
Composer doesn't install or update properly

### ISSUE THREAD

**Issue by t202wes** [codeclimate/php-test-reporter#19]
I can not get composer to install the php-test-reporter library properly.  Our composer.json has this:

  "require-dev" : {
    "satooshi/php-coveralls" : "dev-master",
     "codeclimate/php-test-reporter" : "dev-master"
  }

This is the error we always receive: 

php composer.phar update 

Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for codeclimate/php-test-reporter dev-master -> satisfiable by codeclimate/php-test-reporter[dev-master].
    - codeclimate/php-test-reporter dev-master requires satooshi/php-coveralls 0.6.* -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <http://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

**Comment by nsilberman** [comment]
same issue for me I think. Did you guys found a solution ? 

```
 Problem 1
    - codeclimate/php-test-reporter 0.1.x-dev requires satooshi/php-coveralls 0.6.* -> satisfiable by satooshi/php-coveralls[v0.6.0, v0.6.1].
    - codeclimate/php-test-reporter v0.1.2 requires satooshi/php-coveralls 0.6.* -> satisfiable by satooshi/php-coveralls[v0.6.0, v0.6.1].
    - satooshi/php-coveralls v0.6.0 requires psr/log 1.0.0 -> satisfiable by psr/log[1.0.0].
    - satooshi/php-coveralls v0.6.1 requires psr/log 1.0.0 -> satisfiable by psr/log[1.0.0].
    - Conclusion: don't install psr/log 1.0.0
```

**Comment by mickadoo** [comment]
@nsilberman Do you have a reference to satooshi/php-coveralls from your composer.json? I'm no expert, but removing it fixed my problem.

**Comment by nsilberman** [comment]
@mickadoo nope

**Comment by elazar** [comment]
Potentially related: satooshi/php-coveralls#81

**Comment by jonathancadepowers** [comment]
I'm closing this one out, as we ended up helping everyone above via a [formal support ticket](https://codeclimate.com/help).

In case anyone else runs into these issues, note that we've added info on how to fix the problems to our help docs: http://docs.codeclimate.com/article/220-help-im-having-trouble-with-test-coverage#php_install_error
