### ISSUE TITLE
The SSL workaround code doesn't work in .travis.yml

### ISSUE THREAD

**Issue by brandonsavage** [codeclimate/php-test-reporter#23]
The code provided does not pass linting for YAML valid code.

**Comment by jonathancadepowers** [comment]
@mickadoo Sorry for the long delay in getting back to you here. Good point regarding `bin/test-reporter` versus `vendor/bin/test-reporter`. I added a `Note:` about this to our README: https://github.com/codeclimate/php-test-reporter/blob/master/README.md#known-issue-ssl-certificate-error
