### ISSUE TITLE
Guzzle SSL Certificate Verification Failure on CircleCI

### ISSUE THREAD

**Issue by evilantnie** [codeclimate/php-test-reporter#3]
I'm trying to push coverage results from our CircleCI builds, but the test-reporter step fails at the end with the following error:
```
[Guzzle\Http\Exception\CurlException]                                        
  [curl] 60: server certificate verification failed. CAfile: /home/ubuntu/Sto  
  ck/www/protected/composer_vendor/guzzle/guzzle/src/Guzzle/Http/Resources/ca  
  cert.pem CRLfile: none [url] https://codeclimate.com/test_reports    
```
I've tried upgrading to the latest guzzle version in our composer.json, as well as ensuring that the box has running `update-ca-certs` on the box, but I still get this error.  Any ideas?

**Comment by enygma** [comment]
Okay, so there's something amiss here...when I execute this:

```
openssl s_client -connect codeclimate.com:443
```

I get the response:

```
CONNECTED(00000003)
depth=4 C = SE, O = AddTrust AB, OU = AddTrust External TTP Network, CN = AddTrust External CA Root
verify error:num=19:self signed certificate in certificate chain
verify return:0
```

Note the "self signed certificate in certificate chain" there. So, in going through some of this SSL certificate mess, I noticed something that could cause this error. I wonder if the intermediate certificates were installed correctly for the Code Climate wildcard domain. Most browsers apparently already come with the necessary intermediate certs so they don't error. @pbrisbin or @noahd1 - could you guys check on that and see if those were installed correctly?

This site doesn't show any problems though, so I'm not sure what's up here...
https://www.sslshopper.com/ssl-checker.html#hostname=https://codeclimate.com/test_reports:443

**Comment by ahmadnassri** [comment]
any progress on this? seems like self-signed cert is not the way to go here ... wouldn't you want to use cert with a signing authority backing it?

**Comment by enygma** [comment]
@ahmadnassri it's not that Code Climate's cert is self-signed (it's signed just fine by EssentialSSL's External CA). There's just something in between that's causing issues...either the intermediate certs or something else. I'm not a SSL guru, so I'm just gathering what I can here. Anyone with more skills at identifying the issue is more that welcome to take a crack at it.

**Comment by enygma** [comment]
Okay, @ahmadnassri @atulatri @sun @munkie @evilantnie - can you folks do me a favor? Can you report back what this line gives you on the machines it's **not** working on?

```
php -i | grep 'cURL Information'
```

I'm starting to suspect different curl versions as Travis-CI still runs `7.22.0` and I seem to have `7.30.0`.

**Comment by ahmadnassri** [comment]
@enygma problem only on travis for me

**Comment by enygma** [comment]
I think this could be a curl issue...I'm going to try to build a box with 7.22 installed and see what happens.

**Comment by enygma** [comment]
Well, the bad news is that I compiled a VM with PHP using curl 7.22.0 and ran my test script that fails on Travis...and it worked. Back to the drawing board.

**Comment by enygma** [comment]
After a bit more research (and more reading of the results) I noticed this in the cert chain from the above openssl command:

```
 1 s:/C=SE/O=AddTrust AB/OU=AddTrust External TTP Network/CN=AddTrust External CA Root
   i:/C=SE/O=AddTrust AB/OU=AddTrust External TTP Network/CN=AddTrust External CA Root
```
The issuer and signer are the same. It looks like AddTrust has a self-signed cert for their External CA. That's where that message comes from but it doesn't seem like it should cause the issue with the  `Unexpected response: -60 server certificate verification failed` message. hmm...

**Comment by ahmadnassri** [comment]
wonder if poking any one from the travis team for their vms / settings would help give a repeatable path...

**Comment by enygma** [comment]
So I have a test branch of the php-test-reporter that removes the cURL dependency...I'd be interested to see if it cooperates for anyone else. It works local and on Travis-CI:

https://github.com/enygma/php-test-reporter/tree/remove-curl

**Comment by geshan** [comment]
```
after_script:
  - CODECLIMATE_REPO_TOKEN="..." bin/test-reporter --stdout > codeclimate.json
  - "curl -X POST -d @codeclimate.json -H 'Content-Type: application/json' -H 'User-Agent: Code Climate (PHP Test Reporter v0.1.1)' https://codeclimate.com/test_reports"
```

It there an easy way to run the above commands from a shell script, as the code coverage is just taken into account for master branch I generate the coverage only for master branch. But when I need to post the file I think due to "quotes" the curl does not find the file. How can I call it from a shell script.

**Comment by jonathancadepowers** [comment]
We have now resolved this issue, so it should no longer be necessary to use the cURL work-around. 

Instead, you should now be able to use our [standard configuration](https://github.com/codeclimate/php-test-reporter#installation), by passing your `clover.xml` file to our PHP test reporter directly. This is true for all testing environments, including CIs.

If anyone else runs into a certificate issue, please let us know via [our help form](https://codeclimate.com/help).

**Comment by nunorafaelrocha** [comment]
@jonathancadepowers I still get the certificate errors, but only on the travis CI. Does anyone still have this?

If this was fixed, shouldn't the workaround be removed from the README.md file?

**Comment by jonathancadepowers** [comment]
@nunorafaelrocha We have received a few *new* reports of this recently, so it looks like this issue is unfortunately not fully resolved for all projects, as we had originally thought. Very sorry about that. For now the cURL work-around will continue to work: https://github.com/codeclimate/php-test-reporter#known-issue-ssl-certificate-error
