### ISSUE TITLE
Semantic versioning and new release

### ISSUE THREAD

**Issue by kwn** [codeclimate/php-test-reporter#40]
Hi guys,

What do you think about start using semver for that repo? Also, you could create a new release since the latest release is 22 behind the current master. I think that repo is stable enough to bump it to the 1.0.0 version.

Cheers

**Comment by GordonDiggs** [comment]
@kwn Agreed on the SemVer! I just pushed v0.2.0

**Comment by kwn** [comment]
@GordonDiggs 
:+1: Thanks
