### ISSUE TITLE
Test reporter endpoint is returning a 413 Request Entity Too Large error

### ISSUE THREAD

**Issue by mikealmond** [codeclimate/php-test-reporter#43]
I am trying to send my code coverage report from PhpUnit through the test reporter. I am following the steps defined in [docs](https://github.com/codeclimate/php-test-reporter#usage) and am generating a `codeclimate.json` file. The generated file is only 1.1MB and is being sent via cURL.

In the [troubleshooting documentation](http://docs.codeclimate.com/article/220-help-im-having-trouble-with-test-coverage#413) it states that

> The size of the coverage payload exceeds our limit, which is currently 3MB. Unfortunately we don't yet have a workaround to this issue.

Is that 3MB value incorrect, or am I doing something else wrong?

**Comment by mikealmond** [comment]
Small update on the issue above. It looks like the actual limit in the documentation should be 1MB.

`Content-Length: 1087437` fails.
`Content-Length: 903016` succeeds.

**Comment by dblandin** [comment]
Hey @mikealmond, you're totally right! During a recent infrastructure migration, we lost the setting that bumped the `client_max_body_size` from the default of 1MB to 3MB.

I've updated our configuration and our servers will now accept test coverage payloads of up to 3MB.

Thanks for the report!
