### ISSUE TITLE
Remove dependency on Coveralls

### ISSUE THREAD

**Issue by pbrisbin** [codeclimate/php-test-reporter#6]
We rely on classes from satooshi/php-coveralls for converting Clover XML to the proper JSON payload for our API endpoint. It would be good to just (re)write the logic we do rely on and remove that dependency.

**Example Input**:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<coverage generated="1365848893">
  <project timestamp="1365848893">
    <package name="Hoge">
      <file name="/home/patrick/Code/codeclimate/php-test-reporter/src/CodeClimate/Bundle/TestReporterBundle/ApiClient.php">
        <class name="TestFile" namespace="Hoge">
          <metrics methods="1" coveredmethods="0" conditionals="0" coveredconditionals="0" statements="1" coveredstatements="0" elements="2" coveredelements="0"/>
        </class>
        <line num="6" type="method" name="__construct" crap="1" count="0"/>
        <line num="8" type="stmt" count="0"/>
      </file>
    </package>
  </project>
</coverage>
```

The API endpoint for reporting coverage is shared across all test reporters for all languages, so this format must be maintained.

**Example Output**:

```javascript
{
  "partial": false,
  "run_at": 1365848893,
  "repo_token": "...",
  "environment": {
    "pwd": "\/home\/patrick\/Code\/codeclimate\/php-test-reporter",
    "package_version": "0.1.0-dev"
  },
  "git":{
    "head": "7e3f3495218f92ad5ce847248e306f279b11a9f9",
    "branch": "pb-bundled-cert",
    "committed_at": 1404230153
  },
  "ci_service": "travis",
  "source_files": [{
    "name": "src\/CodeClimate\/Bundle\/TestReporterBundle\/ApiClient.php",
    "blob_id": "272fdc7fbbcd2d99f99db2f4fa59747ed2f35b05",
    "coverage":"[null, 0, null, 1, null, 3, null, 0, ...]"
  },{ 
    // ...
  }]
}
```

**Values in JSON not from XML**:

- Environment information (CWD, token, CI service, etc)
- Git information (head, branch, blob ids, etc)

**Comment by elazar** [comment]
This would seem prudent particularly because php-coveralls recently [relaxed their Symfony dependency versions](https://github.com/satooshi/php-coveralls/commit/5252c82dd2abacfed19b0adc8e4dee1788d11661) and those Symfony dependencies recently updated their minimum PHP version to 5.5.9, which exceeds this repository's [current requirement of 5.3](https://github.com/codeclimate/php-test-reporter/blob/2dd8395f81874333d15de3a598f722997ba42fb5/composer.json#L16):

* symfony/Console@9503491a59ef89b1ce78e1d14716cf6d89817842
* symfony/Yaml@2daf2f6c6dc279117a4fedf32eae34f5d1d18600
* symfony/Config@d3e7b5793623a322b297c4ed5c4b4a13bea62398
* symfony/Stopwatch@e24eab195ce909eb25851fb9bc289f33d2411f3a

**Comment by Ocramius** [comment]
@elazar that doesn't enforce usage of 5.5, no? 2.* versions of the symfony components should work fine.

**Comment by elazar** [comment]
@Ocramius They should, but are not what's being used at this point unless the project using them explicitly sets differing versions. Here's [an example](https://travis-ci.org/chrismou/phergie-irc-plugin-react-audioscrobbler/jobs/46776927) of what I mean. /cc @chrismou

**Comment by elazar** [comment]
Adding these to this repository's `composer.json` file should mitigate the issue described in my original comment (by providing the version upper bound that php-coveralls has removed) until the dependency on php-coveralls can be removed:

```json
{
    "require": {
        "symfony/console": "~2",
        "symfony/yaml": "~2",
        "symfony/config": "~2",
        "symfony/stopwatch": "~2"
    }
}
```

**Comment by dblandin** [comment]
@pbrisbin Is this still a concern?

**Comment by dblandin** [comment]
Going to go ahead and close this issue for now.
