### ISSUE TITLE
Give @localheinz commit bit

### ISSUE THREAD

**Issue by pbrisbin** [codeclimate/php-test-reporter#88]
@localheinz what do you think?

Things wouldn't change too much; still the general PR, review, merge process, but:

- You could make your branches in this repo
- You could merge them yourself (after a :+1:)
- You could/should review and merge other outside contributions
- You could handle tagging and releasing, to some degree

Since we don't have much PHP expertise on the team, we could certainly use another voice steering this repository.

/cc @dblandin @maxjacobson

**Comment by localheinz** [comment]
Ha, sounds awesome!

We at @refinery29 use it in each PHP repository we have, would be nice to help push forward!

**Comment by pbrisbin** [comment]
FYI: as part of inviting our first outside collaborator, I've turned on protected branches and required green status and review before merging.

**Comment by maxjacobson** [comment]
Sounds great to me :)

**Comment by localheinz** [comment]
@pbrisbin 

>FYI: as part of inviting our first outside collaborator, I've turned on protected branches and required green status and review before merging.

This is exactly what I would do, too! 👍

**Comment by pbrisbin** [comment]
Invite sent!

**Comment by dblandin** [comment]
@localheinz Thanks for your contributions! 🎉
